### ISSUE TITLE
Wrong password

### ISSUE THREAD

**Issue by epicslendyz** [SuperPuperSteve/MyAuth#4]
Every time I try to login it's said wrong password even tho it's right

**Comment by ivand-sykt** [comment]
@epicslendyz Give more information (config)

**Comment by epicslendyz** [comment]
if i register the password then quit the game and join back i login and it said my password is wrong

**Comment by ivand-sykt** [comment]
@epicslendyz please post your plugin configuration

**Comment by epicslendyz** [comment]
---
# by SuperPuperSteve (author)
lang_selected: "§bEnglish has been selected"
ingame_only: "§cThis command must be ran in-game only!"
no_permission: "§cYou don't have enough permission"

db_conn_error: "§cFailed to connect to DB: {error}"
db_init: "§eInitializating {type} DB..."
db_success: "§aSuccessfully connected to DB"
db_disconnect: "§eDisconnecting from DB..."
db_wrong: "§cWrong database type: {type}. SQLite will be used instead."

register: "§bPlease, register using /reg <password>"
register_success: "§aYou've successfully registered!"
register_already: "§cYou're already registered"
register_nopass: "§cYou haven't typed password!"

login: "§bPlease, login using /login <password>"
login_auto: "§aYou've authorized automatically!"
login_success: "§aYou've successfully authorized!"
login_already: "§cYou've already authorized!"
login_nopass: "§cYou haven't typed password!"
login_wrongpass: "§cWrong password!"
login_noregister: "§cYou aren't registered yet!"

unregister_nopass: "§cPlease, type password. /unregister <password> <repeat password>"
unregister_mismatch: "§cPasswords doesn't match!"
unregister_success: "§aYou've successfully unregistered!"
unregister_wrong: "§cYou've typed wrong password"

passwd_nonewpass: "§cYou didn't type new password! /chp <old password> <new password> <confirm password>"
passwd_noconfirm: "§cPlease repeat new password"
passwd_nomatch: "§cNew passwords doesn't match!"
passwd_success: "§aYou've successfully changed password to \"{new_password}\"! Please, log in again"

logout_success: "§aYou've successfully logged out!"

myadmin_help: "§6--- MyAuth ---§f
\n/myadmin chp <nick> <password> - change player's password
\n/myadmin info <nick> - player's info"
myadmin_nonick: "§cYou haven't typed nickname!"
myadmin_nopass: "§cYou haven't typed password!"
myadmin_chp: "§aPassword changed for user {nickname}"
myadmin_noplayer: "§cUser {nickname} is not registered"
myadmin_info: "--- Info about {nickname}
\nFirst login: {first_login}
\nLast login: {last_login}
\nIP: {ip}
\nCID: {cid}"
...
sometime it said unknown comment and sometime wrong password

**Comment by ivand-sykt** [comment]
are you kidding me? `config.yml`
