### ISSUE TITLE
Boolean return required

### ISSUE THREAD

**Issue by ggomezz** [SuperPuperSteve/MyAuth#9]
This is the error:

`[01:26:11] [Server thread/CRITICAL]: Unhandled exception executing command 'login ********' in login: Return value of MyAuth\Commands\LoginCommand::onCommand() must be of the type boolean, none returned
[01:26:11] [Server thread/CRITICAL]: TypeError: "Return value of MyAuth\Commands\LoginCommand::onCommand() must be of the type boolean, none returned" (EXCEPTION) in "MyAuth.phar/src/MyAuth/Commands/LoginCommand" at line 44
`

**Comment by ggomezz** [comment]
This server is running PocketMine-MP 1.6.2dev-378 「Unleashed」 implementing API version 3.0.0-ALPHA7 for Minecraft: PE v1.1.0.55 (protocol version 113) (No idea what MyAuth Version)

**Comment by SuperPuperSteve** [comment]
@ggomezz fucking pmmp

**Comment by ggomezz** [comment]
Doesn't stop people from using it, just gives them the critical warning because it is not Boolean. Still usable. 
(This issue is probably what the poggit lint thing is saying)

**Comment by ggomezz** [comment]
Would this work:
`public function onCommand(CommandSender $sender, Command $cmd, string $label, array $args): bool{`

**Comment by ivand-sykt** [comment]
@ggomezz no.

**Comment by ggomezz** [comment]
Oh well, I tried to help

**Comment by ggomezz** [comment]
Alright, I downloaded the master zip and made a few changes to the command folder and it appears to be working now for me:
Logout Command PHP: https://pastebin.com/dLZRxndY
Login Command "": https://pastebin.com/aX2jdjKv
Change Password Command "": https://pastebin.com/rcw7dndv
Register Command "": https://pastebin.com/jGRdbJca
UnRegister Command "": https://pastebin.com/kZwEQRXU
MyAdmin Command "": https://pastebin.com/Q9giau2h

**Comment by ggomezz** [comment]
This MyAdmin Command PHP I tested and is working:
https://pastebin.com/wQ0PbS0a
